# Generated by Django 5.1.2 on 2024-10-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('games', '0003_alter_game_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='games.game'),
        ),
    ]
