# Generated by Django 5.1.2 on 2024-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=100)),
            ],
        ),
    ]
