# Generated by Django 5.1.2 on 2024-10-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='session_id',
            new_name='game_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='session_name',
        ),
    ]
